"""Add REGISTRATION_UPDATED event name

Revision ID: d7f3a8b9c6e2
Revises: c9e8f7a6b5d4
Create Date: 2026-06-15 12:29:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f3a8b9c6e2'
down_revision = 'c9e8f7a6b5d4'
branch_labels = None
depends_on = None

old_options = ('APPLICATION_SUBMITTED', 'INVOICE_GENERATED', 'PAYMENT_COMPLETE', 'PENDING_AUTO_APPROVAL_PROCESSING', 'AUTO_APPROVAL_FULL_REVIEW', 'AUTO_APPROVAL_PROVISIONAL', 'AUTO_APPROVAL_APPROVED', 'FULL_REVIEW_IN_PROGRESS', 'MANUALLY_APPROVED', 'MANUALLY_DENIED', 'MORE_INFORMATION_REQUESTED', 'REGISTRATION_CREATED', 'REGISTRATION_RENEWED', 'CERTIFICATE_ISSUED', 'REGISTRATION_EXPIRED', 'NON_COMPLIANCE_SUSPENDED', 'REGISTRATION_CANCELLED', 'REGISTRATION_APPROVED', 'REGISTRATION_REINSTATED', 'APPLICATION_REVIEWER_ASSIGNED', 'APPLICATION_REVIEWER_UNASSIGNED', 'REGISTRATION_ASSIGNEE_ASSIGNED', 'REGISTRATION_ASSIGNEE_UNASSIGNED', 'NOC_SENT', 'NOC_EXPIRED', 'HOST_APPLICATION_UNIT_ADDRESS_UPDATED', 'HOST_REGISTRATION_UNIT_ADDRESS_UPDATED', 'APPLICATION_DECISION_SET_ASIDE', 'REGISTRATION_DECISION_SET_ASIDE', 'REGISTRATION_DOCUMENT_UPLOADED', 'CONDITIONS_OF_APPROVAL_UPDATED', 'RENEWAL_REMINDER_SENT')
new_options = ('APPLICATION_SUBMITTED', 'INVOICE_GENERATED', 'PAYMENT_COMPLETE', 'PENDING_AUTO_APPROVAL_PROCESSING', 'AUTO_APPROVAL_FULL_REVIEW', 'AUTO_APPROVAL_PROVISIONAL', 'AUTO_APPROVAL_APPROVED', 'FULL_REVIEW_IN_PROGRESS', 'MANUALLY_APPROVED', 'MANUALLY_DENIED', 'MORE_INFORMATION_REQUESTED', 'REGISTRATION_CREATED', 'REGISTRATION_RENEWED', 'CERTIFICATE_ISSUED', 'REGISTRATION_EXPIRED', 'NON_COMPLIANCE_SUSPENDED', 'REGISTRATION_CANCELLED', 'REGISTRATION_APPROVED', 'REGISTRATION_REINSTATED', 'APPLICATION_REVIEWER_ASSIGNED', 'APPLICATION_REVIEWER_UNASSIGNED', 'REGISTRATION_ASSIGNEE_ASSIGNED', 'REGISTRATION_ASSIGNEE_UNASSIGNED', 'NOC_SENT', 'NOC_EXPIRED', 'HOST_APPLICATION_UNIT_ADDRESS_UPDATED', 'HOST_REGISTRATION_UNIT_ADDRESS_UPDATED', 'APPLICATION_DECISION_SET_ASIDE', 'REGISTRATION_DECISION_SET_ASIDE', 'REGISTRATION_DOCUMENT_UPLOADED', 'CONDITIONS_OF_APPROVAL_UPDATED', 'RENEWAL_REMINDER_SENT', 'REGISTRATION_UPDATED')

old_type = sa.Enum(*old_options, name='eventname')
new_type = sa.Enum(*new_options, name='eventname')


def upgrade():
    op.execute('ALTER TYPE eventname RENAME TO tmp_eventname')
    new_type.create(op.get_bind())
    op.execute('ALTER TABLE events ALTER COLUMN event_name TYPE eventname USING event_name::text::eventname')
    op.execute('DROP TYPE tmp_eventname')


def downgrade():
    op.execute('ALTER TYPE eventname RENAME TO tmp_eventname')
    old_type.create(op.get_bind())
    op.execute('ALTER TABLE events ALTER COLUMN event_name TYPE eventname USING event_name::text::eventname')
    op.execute('DROP TYPE tmp_eventname')
